version: "3.9"

services:
  spark-master:
    image: apache/spark:4.1.0-python3
    container_name: spark-master
    hostname: spark-master
    volumes:
      - .:/workspace    
    environment:
      - PYSPARK_PYTHON=python3
      - PYSPARK_DRIVER_PYTHON=python3     
      - SPARK_MODE=master
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.master.Master
    ports:
      - "7077:7077"     # Spark master port
      - "8080:8080"     # Spark master UI
    networks:
      - spark-net

  spark-worker:
    image: apache/spark:4.1.0-python3
    container_name: spark-worker
    depends_on:
      - spark-master
    volumes:
      - .:/workspace      
    environment:
      - PYSPARK_PYTHON=python3
      - PYSPARK_DRIVER_PYTHON=python3    
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077
    ports:
      - "8081:8081"     # Spark worker UI
    networks:
      - spark-net

  spark-notebook:
    build: .
    container_name: spark-notebook
    depends_on:
      - spark-master
    volumes:
      - .:/workspace
# Comment this line if it does not work in Windows      
      - ~/.ssh:/root/.ssh:ro      
    working_dir: /workspace
    environment:
      - JUPYTER_PASSWORD="datacamp"
      - PYSPARK_PYTHON=python3
      - PYSPARK_DRIVER_PYTHON=jupyter
      - PYSPARK_DRIVER_PYTHON_OPTS=notebook
      - SPARK_MASTER_URL=spark://spark-master:7077
    command: >
      jupyter notebook
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --allow-root    
    ports:
      - "8888:8888"
    networks:
      - spark-net

networks:
  spark-net:
    driver: bridge